services:
  postgres:
    container_name: chat-db
    image: postgres:16
    environment:
      POSTGRES_USER: chat
      POSTGRES_PASSWORD: chat
      POSTGRES_DB: chat
    ports:
      - '5431:5432'

  redis:
    container_name: chat-redis
    image: redis:7
    ports:
      - '6370:6379'
